name: linting
on:
  pull_request:
    branches: [master, develop]
jobs:
  linting:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: lint the code
        uses: ricardochaves/python-lint@v1.4.0
        with:
          use-pylint: false
          use-pycodestyle: false
          use-flake8: true
          use-black: false
          use-mypy: false
          use-isort: true
